artifact_location: file:C:/Users/Lenovo/MLOPS/Complete-MLFlow/breat_cancer-rf-hp/0
creation_time: 1734109890000
experiment_id: '0'
last_update_time: 1734109890000
lifecycle_stage: active
name: Default
